name = "BoardGames"
uuid = "a25c074d-a6f8-44e3-8722-7dc1f329dbb4"
authors = ["António Capela"]
version = "0.1.0"

[deps]
BoardGamesGames = "8d3b03d8-dda0-42fb-bf80-a917fc4ec273"
BoardGamesStrategies = "32f2dd74-f74d-434c-9211-e2f9435e7f91"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
